// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-pen-umJqEcC3E_2cgyIcX2GIvZ6COEQ',
    appId: '1:425909407022:web:e82b6957d067c094d8febf',
    messagingSenderId: '425909407022',
    projectId: 'socialmidtermapp',
    authDomain: 'socialmidtermapp.firebaseapp.com',
    storageBucket: 'socialmidtermapp.firebasestorage.app',
    measurementId: 'G-02CGHPLLK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIWyR8fGqMCUA_5QC9poLGPHwnaKOn3HE',
    appId: '1:425909407022:android:018c46cc74cf5077d8febf',
    messagingSenderId: '425909407022',
    projectId: 'socialmidtermapp',
    storageBucket: 'socialmidtermapp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-pen-umJqEcC3E_2cgyIcX2GIvZ6COEQ',
    appId: '1:425909407022:web:0416441e6dad07f4d8febf',
    messagingSenderId: '425909407022',
    projectId: 'socialmidtermapp',
    authDomain: 'socialmidtermapp.firebaseapp.com',
    storageBucket: 'socialmidtermapp.firebasestorage.app',
    measurementId: 'G-SVVEM3TSZK',
  );
}
